import type { Metadata } from "next";
import localFont from "next/font/local";
// import "./globals.css";
import { Toaster } from "@/components/ui/sonner"
import HotelHeroSection from "@/components/hotels/hero-section/HotelHeroSection";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section className="font-sans bg-white text-black">
      <HotelHeroSection />
      {children}
      <Toaster />
    </section>
  );
}
